// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOJRydx3vE17qWOLGObBcXH-NOEiv2WE',
    appId: '1:771828392927:web:8cc150c2c681e0d9391a6a',
    messagingSenderId: '771828392927',
    projectId: 'shopwithusama-5ec33',
    authDomain: 'shopwithusama-5ec33.firebaseapp.com',
    storageBucket: 'shopwithusama-5ec33.appspot.com',
    measurementId: 'G-89CR7WMK12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0lOfWmibQOOPT83EaCuiiB1YMXb_PJDI',
    appId: '1:771828392927:android:344f37c56c25552e391a6a',
    messagingSenderId: '771828392927',
    projectId: 'shopwithusama-5ec33',
    storageBucket: 'shopwithusama-5ec33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0h3KDYhgJezL9ssTC1NX094roB_QckdI',
    appId: '1:771828392927:ios:fad8d103e85a05ed391a6a',
    messagingSenderId: '771828392927',
    projectId: 'shopwithusama-5ec33',
    storageBucket: 'shopwithusama-5ec33.appspot.com',
    androidClientId: '771828392927-a7sn2c2np74gdjbu7b3oe4gbvucqu2ap.apps.googleusercontent.com',
    iosClientId: '771828392927-jl6q3gi1htvcb6961gp65ug0o9kb454j.apps.googleusercontent.com',
    iosBundleId: 'com.shopwithus.shopwithusama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0h3KDYhgJezL9ssTC1NX094roB_QckdI',
    appId: '1:771828392927:ios:fad8d103e85a05ed391a6a',
    messagingSenderId: '771828392927',
    projectId: 'shopwithusama-5ec33',
    storageBucket: 'shopwithusama-5ec33.appspot.com',
    androidClientId: '771828392927-a7sn2c2np74gdjbu7b3oe4gbvucqu2ap.apps.googleusercontent.com',
    iosClientId: '771828392927-jl6q3gi1htvcb6961gp65ug0o9kb454j.apps.googleusercontent.com',
    iosBundleId: 'com.shopwithus.shopwithusama',
  );

}